### ISSUE TITLE
Issue - traceback

### ISSUE THREAD

**Issue by Skulldron** [Vitens/epynet#14]
Hello, I'm trying to run epynet (I'm kinda new to python). I got following issue after trying to solve network (PyCharm). Would you please be so kind and help me to make it work? Thank you in advance.

Traceback (most recent call last):
  File "C:/DEV/1_EDU/epynet/try_epynet.py", line 3, in <module>
    dupa = Network('network.inp')
  File "C:\DEV\Python\lib\site-packages\epynet-0.1-py3.6.egg\epynet\network.py", line 14, in __init__
    self.ep = epanet2.EPANET2()
  File "C:\DEV\Python\lib\site-packages\epynet-0.1-py3.6.egg\epynet\epanet2.py", line 26, in __init__
    self._lib = ctypes.CDLL(dll_path)
  File "C:\DEV\Python\lib\ctypes\__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 193] %1 is not a valid Win32 system app

**Comment by AbelHeinsbroek** [comment]
EPYNET requires a 64 bit version of Python. Could you confirm you are using the right version?
